### ISSUE TITLE
Warn Meldungen im LOG 

### ISSUE THREAD

**Issue by ChrissT23** [pottio/ioBroker.warp#11]
Zu allererst, vielen Dank für den Adapter, das sieht sehr vielversprechend aus. 

Ich habe das Problem das bei beiden wallboxen von mir mit jeweils eigener Instanz der LOG mit folgenden Warn Meldungen voll ist. 

Zuerst zum System. 
Nodejs 14.19.1
NPM 6.14.16
JS Controller 4.0.21 

2x Warp2 Smart 

Die Fehler kommen im Sekundentakt bei beiden Wallboxen. 

`

warp.0 | 2022-04-05 20:06:46.150 | warn | (7047) Object of state "warp.0.evse.low_level_state.gpio" is missing the required property "common.type"
warp.0 | 2022-04-05 20:06:46.078 | warn | (7047) Object of state "warp.0.evse.low_level_state.voltages" is missing the required property "common.type"
warp.0 | 2022-04-05 20:06:46.066 | warn | (7047) Object of state "warp.0.evse.low_level_state.adc_values" is missing the required property "common.type"
warp.0 | 2022-04-05 20:06:45.140 | warn | (7047) Object of state "warp.0.evse.low_level_state.gpio" is missing the required property "common.type"
warp.0 | 2022-04-05 20:06:45.039 | warn | (7047) Object of state "warp.0.evse.low_level_state.voltages" is missing the required property "common.type"
warp.0 | 2022-04-05 20:06:45.019 | warn | (7047) Object of state "warp.0.evse.low_level_state.adc_values" is missing the required property "common.type"
warp.0

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">`

**Comment by pottio** [comment]
Mit einem WARP der ersten Generation kann ich diese Meldung nicht reproduzieren. Werden denn die darunterliegenden States korrekt mit Werten befüllt? Also z.B. für den Kanal "warp.0.evse.low_level_state.voltages":

- warp.0.evse.low_level_state.voltag.cp_pe_before_resistor_pwm_high
- warp.0.evse.low_level_state.voltag.cp_pe_after_resistor_pwm_high
- warp.0.evse.low_level_state.voltag.cp_pe_before_resistor_pwm_low
- warp.0.evse.low_level_state.voltag.cp_pe_after_resistor_pwm_low
- warp.0.evse.low_level_state.voltag.pp_pe
- warp.0.evse.low_level_state.voltag.pos_12v_rail
- warp.0.evse.low_level_state.voltag.neg_12v_rail

**Comment by ChrissT23** [comment]
Nein die Werte sind leer. Die Frage ist ja wofür man die Werte gebrauchen kann. Die eigentlichen DP die ich für mich persönlich brauche, sind da und können geschaltet werden. 
ich habe aktuell den Log Level auf error gestellt und jetzt soweit rumgespielt das ich für mich nichts vermisse.

**Comment by pottio** [comment]
> Nein die Werte sind leer.

Laut [API Beschreibung](https://www.warp-charger.com/api.html#evse_low_level_state) sollte für *.voltages, *.gpio und *.adc_values je ein Array übermittelt werden, dessen Inhalte dann in einzelne States aufgelöst werden. Für den WARP2 scheint die Realität anders auszusehen.
Ich habe nun noch eine Abfrage eingebaut, die unerwartete Werte abfängt und in einen State *.payload schreibt. 

- Ist das Problem mit den Warnungen in der Version 0.0.4 damit behoben? 
- Welche Werte stehen in den States "warp.0.evse.low_level_state.voltages.payload", "warp.0.evse.low_level_state.gpio.payload", "warp.0.evse.low_level_state.adc_values.payload"? 

> Die Frage ist ja wofür man die Werte gebrauchen kann.

Der WARP Charger sendet nach der Verbindungsherstellung alles, was er zu bieten hat - ich möchte die Entscheidung nicht vorwegnehmen, was davon wichtig ist und was nicht.

**Comment by pottio** [comment]
Danke für die Rückmeldung. 
Da zufälligerweise heute eine neue Firmware-Version für den WARP Charger erschienen ist, die zugleich zahlreiche bedeutende API Anpassungen beinhaltet, werde ich zunächst die Anpassungen gemäß der neuen API Dokumentation umsetzen. In diesem Rahmen werde ich das Konzept für die Arrays überarbeiten und somit hoffentlich die Warnungen verhindern.

**Wichtige Anmerkung: Der Adapter in der Version <= 0.0.4 ist nicht kompatibel mit der heute erschienen Firmware-Version 2.0.0**

**Comment by pottio** [comment]
@ChrissT23 
Ich habe nun die Adapter-Version 1.0.0 veröffentlicht. Diese ist nur mit der WARP firmware >= 2.0.0 kompatibel. 
Bitte noch einmal testen und prüfen, ob die Warnungen noch auftreten. Danke!

**Comment by ChrissT23** [comment]
Sieht sehr gut aus ! LOG bleibt sauber, alles ist steuerbar. 

Perfekt Dankeschön !
