### ISSUE TITLE
Support for WARP firmware >= 2.0.0

### ISSUE THREAD

**Issue by pottio** [pottio/ioBroker.warp#12]
A new WARP firmware was released (version 2.0.0) with a lot of breaking changes in the API

**Comment by ChrissT23** [comment]
Ich habe bei tinkerunity.org auch mal einen Thread dazu aufgemacht um auf deinen Adapter aufmerksam zu machen. Dort kam auch schon von den Admins eine kleine Hilfestellung, https://www.tinkerunity.org/topic/7563-warp-in-iobroker/ 
Vielleicht hilft dir das ja die API anzupassen. 

VG
