### ISSUE TITLE
The WarpAdapter reports version conflict despite correct version

### ISSUE THREAD

**Issue by Gelbwichtel** [pottio/ioBroker.warp#26]
When starting the WarpAdapter with version 1.0.1 the message appears that the firmware >= 2.0.0 must be installed.

![image](https://user-images.githubusercontent.com/71406061/166552815-3101222c-8a64-4b8a-a1ee-3256a3fe1ba8.png)

But the http request returns the requested version:

{"firmware":"2.0.1-624eeb29","config":"2.0.0"}

The following constellation is present in the firmware:

![image](https://user-images.githubusercontent.com/71406061/166553234-1eb23067-c207-4c92-a07b-2eba13b14acc.png)

Unfortunately, I have no more idea how to get the adapter to work.

The older version with the 1.9 firmware still worked.

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 4.0.23
 - Node version: v14.19.1

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**Comment by Gelbwichtel** [comment]
Auch mit der neuen Warp Firmware vom 3.5. kommt der gleiche Fehler

{"firmware":"2.0.3-626fdf13","config":"2.0.0"}

<html>
<body>


warp.0 | 2022-05-03 20:05:06.920 | info | [Main] WARP adapter initialized
-- | -- | -- | --
warp.0 | 2022-05-03 20:05:06.874 | warn | State "warp.0.info.version" has no existing object, this might lead to an error in future versions
warp.0 | 2022-05-03 20:05:06.862 | info | [WarpService] Initialized
warp.0 | 2022-05-03 20:05:06.862 | error | [WarpService] Initializing failed \| Error=Error: Unable to receive meta information from WARP. Please make sure firmware version >= 2.0.0 is installed on your WARP charger
warp.0 | 2022-05-03 20:05:06.861 | error | [WarpClient] Retrieving meta information failed \| Error=Error: Request failed with status code 401
warp.0 | 2022-05-03 20:05:06.786 | debug | [WarpClient] GET: http://192.168.178.186/info/version
warp.0 | 2022-05-03 20:05:06.784 | debug | [WarpClient] Need credentials. Authorize with digest access authentication
warp.0 | 2022-05-03 20:05:06.663 | debug | [WarpClient] Check credentials and authorize if needed
warp.0 | 2022-05-03 20:05:06.662 | info | [WarpClient] Retrieve meta information for adapter startup from WARP charger
warp.0 | 2022-05-03 20:05:06.662 | info | [WarpClient] Initialized
warp.0 | 2022-05-03 20:05:06.661 | debug | [WarpClient] WARP charger api base path: 'http://192.168.178.186'. Websocket base path: 'ws://192.168.178.186'
warp.0 | 2022-05-03 20:05:06.661 | info | [WarpClient] Initializing
warp.0 | 2022-05-03 20:05:06.661 | info | [WarpService] Initializing
warp.0 | 2022-05-03 20:05:06.660 | debug | [Main] Adapter version on last adapter execution: '1.0.1'
warp.0 | 2022-05-03 20:05:06.608 | debug | [Main] Auth enabled. Decrypt password
warp.0 | 2022-05-03 20:05:06.401 | info | [Main] Start initializing WARP adapter
warp.0 | 2022-05-03 20:05:06.358 | info | starting. Version 1.0.1 (non-npm: pottio/ioBroker.warp#114655aed8af854f996094c99387f550e92362e2) in /opt/iobroker/node_modules/iobroker.warp, node: v14.19.1, js-controller: 4.0.23


</body>
</html>

**Comment by pottio** [comment]
Der Fehler 401 deutet darauf hin, dass die Authentifizierung nicht richtig funktioniert. Scheinbar ist im WARP unter _System_ > _Benutzerverwaltung_ die _Anmeldung aktiviert_. Bitte einmal überprüfen, ob Benutzername und Passwort in den Adaptereinstellungen zu einem der konfigurierten Nutzer im WARP passen.
