### ISSUE TITLE
Invalid version of js-controller. Required >=2.0.0. Current 4.0.23

### ISSUE THREAD

**Issue by CSC3000** [pottio/ioBroker.warp#44]
I want to install the adapter and get this message!
"Invalid version of js controller. Required >=2.0.0. Current 4.0.23"
A little crazy!
4.0.23 is bigger than 2.0.0

**Comment by pottio** [comment]
I have also isntalled the js controller with version 4.0.23. The adapter works as expected. It looks like an issue of your specific installation. Please check if your ioBroker is corretly installed and up to date.

**Comment by CSC3000** [comment]
I had the ioroker installation repaired once, now it works. Sorry!

Best regards

Christian

 

Von: pottio ***@***.***> 
Gesendet: Dienstag, 7. Juni 2022 20:56
An: pottio/ioBroker.warp ***@***.***>
Cc: CSC ***@***.***>; Author ***@***.***>
Betreff: Re: [pottio/ioBroker.warp] Invalid version of js-controller. Required >=2.0.0. Current 4.0.23 (Issue #44)

 

I have also isntalled the js controller with version 4.0.23. The adapter works as expected. It looks like an issue of your specific installation. Please check if your ioBroker is corretly installed and up to date.
